import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500'],
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: "Landing one-0-one | Best Landing Page Designs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <script src="../path/to/flowbite/dist/flowbite.min.js"></script> */}
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
